"""Script schema and filesystem queue.

Scripts are never generated by an API call here. They're written directly as
JSON files into scripts_queue/pending/ (batch-written interactively via Claude
Code). This module only validates, loads, and consumes them.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from pipeline.config import QUEUE_PENDING_DIR, QUEUE_USED_DIR

REQUIRED_SCENE_FIELDS = {"narration", "visual_keyword", "duration_hint", "short_worthy"}
REQUIRED_SCRIPT_FIELDS = {"id", "title", "description", "tags", "scenes"}


@dataclass
class Scene:
    narration: str
    visual_keyword: str
    duration_hint: float
    short_worthy: bool = False


@dataclass
class Script:
    id: str
    title: str
    description: str
    tags: list[str] = field(default_factory=list)
    scenes: list[Scene] = field(default_factory=list)

    @property
    def hook(self) -> Scene:
        return self.scenes[0]

    @property
    def outro(self) -> Scene:
        return self.scenes[-1]

    @property
    def body_scenes(self) -> list[Scene]:
        return self.scenes[1:-1]

    @property
    def short_scenes(self) -> list[Scene]:
        """Hook always included; body/outro scenes only if flagged short_worthy."""
        return [self.hook] + [s for s in self.scenes[1:] if s.short_worthy]

    @property
    def short_scene_indices(self) -> list[int]:
        """Same selection as short_scenes, but as indices into self.scenes —
        used to pull matching SceneAudio/BrollClip by position."""
        return [0] + [i for i, s in enumerate(self.scenes[1:], start=1) if s.short_worthy]

    def total_duration(self) -> float:
        return sum(s.duration_hint for s in self.scenes)


class ScriptValidationError(ValueError):
    pass


def validate(data: dict) -> Script:
    missing = REQUIRED_SCRIPT_FIELDS - data.keys()
    if missing:
        raise ScriptValidationError(f"script missing required fields: {sorted(missing)}")

    scenes_data = data["scenes"]
    if not isinstance(scenes_data, list) or len(scenes_data) < 2:
        raise ScriptValidationError("script needs at least 2 scenes (hook + outro)")

    scenes = []
    for i, scene_data in enumerate(scenes_data):
        missing_scene = REQUIRED_SCENE_FIELDS - scene_data.keys()
        if missing_scene:
            raise ScriptValidationError(f"scene {i} missing fields: {sorted(missing_scene)}")
        scenes.append(
            Scene(
                narration=scene_data["narration"],
                visual_keyword=scene_data["visual_keyword"],
                duration_hint=float(scene_data["duration_hint"]),
                short_worthy=bool(scene_data["short_worthy"]),
            )
        )

    return Script(
        id=data["id"],
        title=data["title"],
        description=data["description"],
        tags=list(data.get("tags", [])),
        scenes=scenes,
    )


def to_dict(script: Script) -> dict:
    return {
        "id": script.id,
        "title": script.title,
        "description": script.description,
        "tags": script.tags,
        "scenes": [
            {
                "narration": s.narration,
                "visual_keyword": s.visual_keyword,
                "duration_hint": s.duration_hint,
                "short_worthy": s.short_worthy,
            }
            for s in script.scenes
        ],
    }


def load_next_pending(queue_dir: Path = QUEUE_PENDING_DIR) -> Optional[tuple[Path, Script]]:
    """Returns (path, Script) for the oldest queued file, or None if the queue is empty."""
    pending = sorted(p for p in queue_dir.glob("*.json"))
    if not pending:
        return None
    path = pending[0]
    data = json.loads(path.read_text())
    return path, validate(data)


def mark_used(path: Path, used_dir: Path = QUEUE_USED_DIR) -> Path:
    used_dir.mkdir(parents=True, exist_ok=True)
    dest = used_dir / path.name
    path.rename(dest)
    return dest
