"""Script schema and filesystem queue.

Scripts are never generated by an API call here. They're written directly as
JSON files into scripts_queue/pending/ (batch-written interactively via Claude
Code). This module only validates, loads, and consumes them.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from pipeline.config import QUEUE_PENDING_DIR, QUEUE_USED_DIR

REQUIRED_SCENE_FIELDS = {"narration", "on_screen_text", "duration_hint"}
REQUIRED_SCRIPT_FIELDS = {"id", "title", "description", "tags", "scenes"}


@dataclass
class Scene:
    narration: str
    on_screen_text: str
    duration_hint: float
    # Optional richer visual description used only for the AI illustration
    # prompt (e.g. "a small rabbit squeezing through a narrow fence gap,
    # determined expression") — on_screen_text is a short chapter-title-style
    # label and produces vaguer images on its own. Falls back to
    # on_screen_text when left blank.
    visual: str = ""

    @property
    def image_concept(self) -> str:
        return self.visual or self.on_screen_text


@dataclass
class Script:
    id: str
    title: str
    description: str
    tags: list[str] = field(default_factory=list)
    scenes: list[Scene] = field(default_factory=list)
    # A detailed, reusable physical description of the story's protagonist
    # (fur/hair color, clothing, distinguishing features) — repeated into
    # every scene's AI image prompt (see pipeline.ai_image.build_prompt) so
    # independently-generated scenes look like the same character. Optional/
    # blank for scripts without a clear single protagonist, or written
    # before this field existed.
    character_reference: str = ""
    # 1-based position within an ongoing serialized track (see
    # pipeline.config.Track.serialized); 0 for standalone, non-serialized
    # stories.
    episode_number: int = 0

    @property
    def hook(self) -> Scene:
        return self.scenes[0]

    @property
    def outro(self) -> Scene:
        return self.scenes[-1]

    @property
    def body_scenes(self) -> list[Scene]:
        return self.scenes[1:-1]

    def total_duration(self) -> float:
        return sum(s.duration_hint for s in self.scenes)

    def badge_text(self, scene_index: int) -> str:
        """The on-screen progress badge for a scene, e.g. 'PART 2/6 · THE
        OLD OWL' for a body scene, or just the scene's on_screen_text for
        the hook/outro. Numbering reflects position in the full script, so
        a Short that only includes a subset of scenes still shows correct
        global numbers (e.g. 'PART 4/6') rather than renumbering 1..N."""
        scene = self.scenes[scene_index]
        if scene_index == 0 or scene_index == len(self.scenes) - 1:
            return scene.on_screen_text
        part_number = scene_index
        total_parts = len(self.body_scenes)
        return f"PART {part_number}/{total_parts} · {scene.on_screen_text}"


class ScriptValidationError(ValueError):
    pass


def validate(data: dict) -> Script:
    missing = REQUIRED_SCRIPT_FIELDS - data.keys()
    if missing:
        raise ScriptValidationError(f"script missing required fields: {sorted(missing)}")

    scenes_data = data["scenes"]
    if not isinstance(scenes_data, list) or len(scenes_data) < 2:
        raise ScriptValidationError("script needs at least 2 scenes (hook + outro)")

    scenes = []
    for i, scene_data in enumerate(scenes_data):
        missing_scene = REQUIRED_SCENE_FIELDS - scene_data.keys()
        if missing_scene:
            raise ScriptValidationError(f"scene {i} missing fields: {sorted(missing_scene)}")
        scenes.append(
            Scene(
                narration=scene_data["narration"],
                on_screen_text=scene_data["on_screen_text"],
                duration_hint=float(scene_data["duration_hint"]),
                visual=scene_data.get("visual", ""),
            )
        )

    return Script(
        id=data["id"],
        title=data["title"],
        description=data["description"],
        tags=list(data.get("tags", [])),
        scenes=scenes,
        character_reference=data.get("character_reference", ""),
        episode_number=int(data.get("episode_number", 0)),
    )


def to_dict(script: Script) -> dict:
    return {
        "id": script.id,
        "title": script.title,
        "description": script.description,
        "tags": script.tags,
        "character_reference": script.character_reference,
        "episode_number": script.episode_number,
        "scenes": [
            {
                "narration": s.narration,
                "on_screen_text": s.on_screen_text,
                "duration_hint": s.duration_hint,
                "visual": s.visual,
            }
            for s in script.scenes
        ],
    }


def load_next_pending(queue_dir: Path = QUEUE_PENDING_DIR) -> Optional[tuple[Path, Script]]:
    """Returns (path, Script) for the oldest queued file, or None if the queue is empty."""
    pending = sorted(p for p in queue_dir.glob("*.json"))
    if not pending:
        return None
    path = pending[0]
    data = json.loads(path.read_text())
    return path, validate(data)


def mark_used(path: Path, used_dir: Path = QUEUE_USED_DIR) -> Path:
    used_dir.mkdir(parents=True, exist_ok=True)
    dest = used_dir / path.name
    path.rename(dest)
    return dest
